/*
 * This file was generated automatically by xsubpp version 1.9508 from the 
 * contents of Speech.xs. Do not edit this file, edit Speech.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Speech.xs"
/* $Header: /cvsroot/macperl/perl/macos/ext/Mac/Speech/Speech.xs,v 1.3 2002/11/13 02:04:53 pudge Exp $
 *
 *    Copyright (c) 1996 Matthias Neeracher
 *
 *    You may distribute under the terms of the Perl Artistic License,
 *    as specified in the README file.
 *
 * $Log: Speech.xs,v $
 * Revision 1.3  2002/11/13 02:04:53  pudge
 * Aieeeeee!  Big ol' Carbon update.
 *
 * Revision 1.2  2000/09/09 22:18:28  neeri
 * Dynamic libraries compile under 5.6
 *
 * Revision 1.1  2000/08/14 03:39:33  neeri
 * Checked into Sourceforge
 *
 * Revision 1.4  1998/04/07 01:03:15  neeri
 * MacPerl 5.2.0r4b1
 *
 * Revision 1.3  1997/11/18 00:53:21  neeri
 * MacPerl 5.1.5
 *
 * Revision 1.2  1997/08/08 16:39:30  neeri
 * MacPerl 5.1.4b1 + time() fix
 *
 * Revision 1.1  1997/04/07 20:50:45  neeri
 * Synchronized with MacPerl 5.1.4a1
 *
 */

#define MAC_CONTEXT

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#ifndef MACOS_TRADITIONAL
#include "../Carbon.h"
#endif
#include <Types.h>
#include <Memory.h>
#include <Speech.h>

#ifndef __CFM68K__
#include <FixMath.h>
#else
#define fixed1				((Fixed) 0x00010000L)
#define fract1				((Fract) 0x40000000L)
#define positiveInfinity	((long)  0x7FFFFFFFL)
#define negativeInfinity	((long)  0x80000000L)

extern pascal long double Frac2X(Fract x) = 0xA845;
extern pascal long double Fix2X(Fixed x) = 0xA843;
extern pascal Fixed X2Fix(long double x) = 0xA844;
extern pascal Fract X2Frac(long double x) = 0xA846;
#endif

#ifdef __CFM68K__

#undef FOURWORDINLINE
#define FOURWORDINLINE(w1,w2,w3,w4)  = {w1,w2,w3,w4}

extern pascal NumVersion SpeechManagerVersion(void)
 FOURWORDINLINE(0x203C, 0x0000, 0x000C, 0xA800);

extern pascal OSErr MakeVoiceSpec(OSType creator, OSType id, VoiceSpec *voice)
 FOURWORDINLINE(0x203C, 0x0604, 0x000C, 0xA800);

extern pascal OSErr CountVoices(short *numVoices)
 FOURWORDINLINE(0x203C, 0x0108, 0x000C, 0xA800);

extern pascal OSErr GetIndVoice(short index, VoiceSpec *voice)
 FOURWORDINLINE(0x203C, 0x030C, 0x000C, 0xA800);

extern pascal OSErr GetVoiceDescription(const VoiceSpec *voice, VoiceDescription *info, long infoLength)
 FOURWORDINLINE(0x203C, 0x0610, 0x000C, 0xA800);

extern pascal OSErr GetVoiceInfo(const VoiceSpec *voice, OSType selector, void *voiceInfo)
 FOURWORDINLINE(0x203C, 0x0614, 0x000C, 0xA800);

extern pascal OSErr NewSpeechChannel(VoiceSpec *voice, SpeechChannel *chan)
 FOURWORDINLINE(0x203C, 0x0418, 0x000C, 0xA800);

extern pascal OSErr DisposeSpeechChannel(SpeechChannel chan)
 FOURWORDINLINE(0x203C, 0x021C, 0x000C, 0xA800);

extern pascal OSErr SpeakString(ConstStr255Param s)
 FOURWORDINLINE(0x203C, 0x0220, 0x000C, 0xA800);

extern pascal OSErr SpeakText(SpeechChannel chan, const void * textBuf, unsigned long textBytes)
 FOURWORDINLINE(0x203C, 0x0624, 0x000C, 0xA800);

extern pascal OSErr SpeakBuffer(SpeechChannel chan, const void * textBuf, unsigned long textBytes, long controlFlags)
 FOURWORDINLINE(0x203C, 0x0828, 0x000C, 0xA800);

extern pascal OSErr StopSpeech(SpeechChannel chan)
 FOURWORDINLINE(0x203C, 0x022C, 0x000C, 0xA800);

extern pascal OSErr StopSpeechAt(SpeechChannel chan, long whereToStop)
 FOURWORDINLINE(0x203C, 0x0430, 0x000C, 0xA800);

extern pascal OSErr PauseSpeechAt(SpeechChannel chan, long whereToPause)
 FOURWORDINLINE(0x203C, 0x0434, 0x000C, 0xA800);

extern pascal OSErr ContinueSpeech(SpeechChannel chan)
 FOURWORDINLINE(0x203C, 0x0238, 0x000C, 0xA800);

extern pascal short SpeechBusy(void)
 FOURWORDINLINE(0x203C, 0x003C, 0x000C, 0xA800);

extern pascal short SpeechBusySystemWide(void)
 FOURWORDINLINE(0x203C, 0x0040, 0x000C, 0xA800);

extern pascal OSErr SetSpeechRate(SpeechChannel chan, Fixed rate)
 FOURWORDINLINE(0x203C, 0x0444, 0x000C, 0xA800);

extern pascal OSErr GetSpeechRate(SpeechChannel chan, Fixed *rate)
 FOURWORDINLINE(0x203C, 0x0448, 0x000C, 0xA800);

extern pascal OSErr SetSpeechPitch(SpeechChannel chan, Fixed pitch)
 FOURWORDINLINE(0x203C, 0x044C, 0x000C, 0xA800);

extern pascal OSErr GetSpeechPitch(SpeechChannel chan, Fixed *pitch)
 FOURWORDINLINE(0x203C, 0x0450, 0x000C, 0xA800);

extern pascal OSErr SetSpeechInfo(SpeechChannel chan, OSType selector, const void *speechInfo)
 FOURWORDINLINE(0x203C, 0x0654, 0x000C, 0xA800);

extern pascal OSErr GetSpeechInfo(SpeechChannel chan, OSType selector, void *speechInfo)
 FOURWORDINLINE(0x203C, 0x0658, 0x000C, 0xA800);

extern pascal OSErr TextToPhonemes(SpeechChannel chan, const void * textBuf, unsigned long textBytes, Handle phonemeBuf, long *phonemeBytes)
 FOURWORDINLINE(0x203C, 0x0A5C, 0x000C, 0xA800);

extern pascal OSErr UseDictionary(SpeechChannel chan, Handle dictionary)
 FOURWORDINLINE(0x203C, 0x0460, 0x000C, 0xA800);

#endif

#define SpeechFail(error)	if (gMacPerl_OSErr = (error)) { XSRETURN_UNDEF; } else 0

#line 152 "Speech.c"
XS(XS_Mac__Speech_SpeechManagerVersion)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Mac::Speech::SpeechManagerVersion()");
    {
	NumVersion	RETVAL;

	RETVAL = SpeechManagerVersion();
	ST(0) = sv_newmortal();
	sv_setref_pvn(ST(0), "NumVersion", (void*)&RETVAL, sizeof(NumVersion));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_CountVoices)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Mac::Speech::CountVoices()");
    {
	short	RETVAL;
	dXSTARG;
#line 161 "Speech.xs"
	SpeechFail(CountVoices(&RETVAL));
#line 178 "Speech.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_GetIndVoice)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mac::Speech::GetIndVoice(index)");
    {
	short	index = (short)SvIV(ST(0));
	VoiceSpec	RETVAL;
#line 173 "Speech.xs"
	SpeechFail(GetIndVoice(index, &RETVAL));
#line 194 "Speech.c"
	ST(0) = sv_newmortal();
	sv_setref_pvn(ST(0), "VoiceSpec", (void*)&RETVAL, sizeof(VoiceSpec));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_GetVoiceDescription)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mac::Speech::GetVoiceDescription(voice)");
    {
	VoiceSpec	voice;
	VoiceDescription	RETVAL;

	if (sv_isa(ST(0), "VoiceSpec"))
	    memcpy(&voice, SvPV_nolen((SV*)SvRV(ST(0))), sizeof(VoiceSpec));
	else
	    croak("voice is not of type VoiceSpec");
#line 185 "Speech.xs"
	SpeechFail(GetVoiceDescription(&voice, &RETVAL, sizeof(RETVAL)));
#line 216 "Speech.c"
	ST(0) = sv_newmortal();
	sv_setref_pvn(ST(0), "VoiceDescription", (void*)&RETVAL, sizeof(VoiceDescription));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_NewSpeechChannel)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mac::Speech::NewSpeechChannel(voice)");
    {
	VoiceSpec	voice;
	SpeechChannel	RETVAL;
	dXSTARG;

	if (sv_isa(ST(0), "VoiceSpec"))
	    memcpy(&voice, SvPV_nolen((SV*)SvRV(ST(0))), sizeof(VoiceSpec));
	else
	    croak("voice is not of type VoiceSpec");
#line 197 "Speech.xs"
	SpeechFail(NewSpeechChannel(&voice, &RETVAL));
#line 239 "Speech.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_DisposeSpeechChannel)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mac::Speech::DisposeSpeechChannel(chan)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	MacOSRet	RETVAL;
	dXSTARG;

	RETVAL = DisposeSpeechChannel(chan);
	XSprePUSH; PUSHi((IV)!(gMacPerl_OSErr = (short)(RETVAL)));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_SpeakString)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mac::Speech::SpeakString(s)");
    {
	Str255	s;
	MacOSRet	RETVAL;
	dXSTARG;

	MacPerl_CopyC2P(SvPV_nolen(ST(0)), s);

	RETVAL = SpeakString(s);
	XSprePUSH; PUSHi((IV)!(gMacPerl_OSErr = (short)(RETVAL)));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_SpeakText)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Mac::Speech::SpeakText(chan, text)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	SV *	text = ST(1);
	MacOSRet	RETVAL;
	dXSTARG;
#line 226 "Speech.xs"
	{
		void *	textPtr;
		STRLEN	textSize;

		textPtr = 	SvPV(text, textSize);
		RETVAL	= 	SpeakText(chan, textPtr, textSize);
	}
#line 297 "Speech.c"
	XSprePUSH; PUSHi((IV)!(gMacPerl_OSErr = (short)(RETVAL)));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_SpeakBuffer)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Mac::Speech::SpeakBuffer(chan, text, controlFlags)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	SV *	text = ST(1);
	long	controlFlags = (long)SvIV(ST(2));
	MacOSRet	RETVAL;
	dXSTARG;
#line 246 "Speech.xs"
	{
		void *	textPtr;
		STRLEN	textSize;

		textPtr = 	SvPV(text, textSize);
		RETVAL	= 	SpeakBuffer(chan, textPtr, textSize, controlFlags);
	}
#line 322 "Speech.c"
	XSprePUSH; PUSHi((IV)!(gMacPerl_OSErr = (short)(RETVAL)));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_StopSpeech)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mac::Speech::StopSpeech(chan)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	MacOSRet	RETVAL;
	dXSTARG;

	RETVAL = StopSpeech(chan);
	XSprePUSH; PUSHi((IV)!(gMacPerl_OSErr = (short)(RETVAL)));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_StopSpeechAt)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Mac::Speech::StopSpeechAt(chan, whereToStop)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	long	whereToStop = (long)SvIV(ST(1));
	MacOSRet	RETVAL;
	dXSTARG;

	RETVAL = StopSpeechAt(chan, whereToStop);
	XSprePUSH; PUSHi((IV)!(gMacPerl_OSErr = (short)(RETVAL)));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_PauseSpeechAt)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Mac::Speech::PauseSpeechAt(chan, whereToPause)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	long	whereToPause = (long)SvIV(ST(1));
	MacOSRet	RETVAL;
	dXSTARG;

	RETVAL = PauseSpeechAt(chan, whereToPause);
	XSprePUSH; PUSHi((IV)!(gMacPerl_OSErr = (short)(RETVAL)));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_ContinueSpeech)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mac::Speech::ContinueSpeech(chan)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	MacOSRet	RETVAL;
	dXSTARG;

	RETVAL = ContinueSpeech(chan);
	XSprePUSH; PUSHi((IV)!(gMacPerl_OSErr = (short)(RETVAL)));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_SpeechBusy)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Mac::Speech::SpeechBusy()");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = SpeechBusy();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_SpeechBusySystemWide)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Mac::Speech::SpeechBusySystemWide()");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = SpeechBusySystemWide();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_SetSpeechRate)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Mac::Speech::SetSpeechRate(chan, rate)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	Fixed	rate = X2Fix(SvNV(ST(1)));
	MacOSRet	RETVAL;
	dXSTARG;

	RETVAL = SetSpeechRate(chan, rate);
	XSprePUSH; PUSHi((IV)!(gMacPerl_OSErr = (short)(RETVAL)));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_GetSpeechRate)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mac::Speech::GetSpeechRate(chan)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	Fixed	RETVAL;
	dXSTARG;
#line 321 "Speech.xs"
	SpeechFail(GetSpeechRate(chan, &RETVAL));
#line 452 "Speech.c"
	XSprePUSH; PUSHn(Fix2X(RETVAL));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_SetSpeechPitch)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Mac::Speech::SetSpeechPitch(chan, pitch)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	Fixed	pitch = X2Fix(SvNV(ST(1)));
	MacOSRet	RETVAL;
	dXSTARG;

	RETVAL = SetSpeechPitch(chan, pitch);
	XSprePUSH; PUSHi((IV)!(gMacPerl_OSErr = (short)(RETVAL)));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_GetSpeechPitch)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Mac::Speech::GetSpeechPitch(chan)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	Fixed	RETVAL;
	dXSTARG;
#line 342 "Speech.xs"
	SpeechFail(GetSpeechPitch(chan, &RETVAL));
#line 486 "Speech.c"
	XSprePUSH; PUSHn(Fix2X(RETVAL));
    }
    XSRETURN(1);
}

XS(XS_Mac__Speech_TextToPhonemes)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Mac::Speech::TextToPhonemes(chan, text)");
    {
	SpeechChannel	chan = (SpeechChannel)SvIV(ST(0));
	SV *	text = ST(1);
	SV *	RETVAL;
#line 354 "Speech.xs"
	{
		void *	textPtr;
		STRLEN	textSize;
		long	phonSize;
		Handle	h;

		textPtr = 	SvPV(text, textSize);
		h = NewHandle(textSize*3+1024);
		SpeechFail(TextToPhonemes(chan, textPtr, textSize, h, &phonSize));
		HLock(h);
		RETVAL	= 	newSVpv(*h, phonSize);
		DisposeHandle(h);
	}
#line 515 "Speech.c"
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Mac__Speech)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Mac::Speech::SpeechManagerVersion", XS_Mac__Speech_SpeechManagerVersion, file);
        newXS("Mac::Speech::CountVoices", XS_Mac__Speech_CountVoices, file);
        newXS("Mac::Speech::GetIndVoice", XS_Mac__Speech_GetIndVoice, file);
        newXS("Mac::Speech::GetVoiceDescription", XS_Mac__Speech_GetVoiceDescription, file);
        newXS("Mac::Speech::NewSpeechChannel", XS_Mac__Speech_NewSpeechChannel, file);
        newXS("Mac::Speech::DisposeSpeechChannel", XS_Mac__Speech_DisposeSpeechChannel, file);
        newXS("Mac::Speech::SpeakString", XS_Mac__Speech_SpeakString, file);
        newXS("Mac::Speech::SpeakText", XS_Mac__Speech_SpeakText, file);
        newXS("Mac::Speech::SpeakBuffer", XS_Mac__Speech_SpeakBuffer, file);
        newXS("Mac::Speech::StopSpeech", XS_Mac__Speech_StopSpeech, file);
        newXS("Mac::Speech::StopSpeechAt", XS_Mac__Speech_StopSpeechAt, file);
        newXS("Mac::Speech::PauseSpeechAt", XS_Mac__Speech_PauseSpeechAt, file);
        newXS("Mac::Speech::ContinueSpeech", XS_Mac__Speech_ContinueSpeech, file);
        newXS("Mac::Speech::SpeechBusy", XS_Mac__Speech_SpeechBusy, file);
        newXS("Mac::Speech::SpeechBusySystemWide", XS_Mac__Speech_SpeechBusySystemWide, file);
        newXS("Mac::Speech::SetSpeechRate", XS_Mac__Speech_SetSpeechRate, file);
        newXS("Mac::Speech::GetSpeechRate", XS_Mac__Speech_GetSpeechRate, file);
        newXS("Mac::Speech::SetSpeechPitch", XS_Mac__Speech_SetSpeechPitch, file);
        newXS("Mac::Speech::GetSpeechPitch", XS_Mac__Speech_GetSpeechPitch, file);
        newXS("Mac::Speech::TextToPhonemes", XS_Mac__Speech_TextToPhonemes, file);
    XSRETURN_YES;
}

